### ISSUE TITLE
Can I get access to your aircraft flight data?

### ISSUE THREAD

**Issue by lemonuncle926** [jonasre/flyDetect#1]
Dear Sir,

I hope this message finds you well. I am currently engaged in research related to aircraft flight mode recognition and came across your paper as well as the code on your GitHub repository. I find your work highly valuable and believe it could greatly benefit my own research. However, I currently lack the necessary dataset to proceed with my work.

With that in mind, I would like to respectfully inquire whether it would be possible to obtain the aircraft flight dataset mentioned in your paper. I understand the sensitivity of such data and assure you that I will handle it with the utmost care and confidentiality. Your assistance in this matter would be greatly appreciated.

Thank you very much for considering my request. I look forward to hearing from you.

Best regards,
Minto Eliot

**Comment by jonasre** [comment]
Hi,

I'm sorry for not getting back to you sooner. The dataset is a collection of flights recorded by multiple people. As such, I cannot consent on behalf of the data collectors. Therefore, I'm afraid I cannot share the dataset.

Best of luck with your research.
