### ISSUE TITLE
Request for Access to Experimental Dataset

### ISSUE THREAD

**Issue by xmr98** [jonasre/flyDetect#2]
Dear flyDetect Team,

I hope this message finds you well.

I am currently working on a research project related to flight mode detection, and I came across your impressive work on the flyDetect project on GitHub. Your findings are highly relevant to my research.

To further validate and extend your work, I would like to request access to the experimental dataset mentioned in your paper. If possible, could you provide the dataset or guide me on how I might obtain it?

Thank you very much for your time and assistance. I look forward to your response.

Haiyong Luo
 Institute of Computing, Chinese Academy of Sciences
yhluo@ict.ac.cn & xmr2015211989@bupt.edu.cn

**Comment by jonasre** [comment]
Hi,

As mentioned in #1, the dataset is a collection of flights recorded by multiple people. As such, I cannot consent on behalf of the data collectors to provide you with the data. I'm sorry that I cannot assist you further in this matter.

If you want to create your own dataset, feel free to use [SensorRecord](https://play.google.com/store/apps/details?id=no.uio.ifi.jonaspr.sensorrecord) which I created for this very purpose. The code for the app is open-source and available [here](https://github.com/jonasre/SensorRecord).

Best of luck with your research.
